### ISSUE TITLE
Server Won't Start

### ISSUE THREAD

**Issue by sarifynna** [haoict/time-in-a-bottle#1]
Hi there! So glad to see this mod as this is one of my favorite items from the random things mod. Works great in SP but when I try to start my server with this mod it fails.

[2021-02-11-1.log](https://github.com/haoict/time-in-a-bottle/files/5969144/2021-02-11-1.log)

**Comment by haoict** [comment]
Hi,
Thank you very much for reporting this issue. I fixed it and submitted a new version to CurseForge.
You can get it here now: https://github.com/haoict/time-in-a-bottle/releases/tag/v1.0.1
