### ISSUE TITLE
Cant hold more than one TIAB, unless they are all synced together

### ISSUE THREAD

**Issue by TacocaTYT** [haoict/time-in-a-bottle#5]
The TIAB will not tick in seconds past the number displayed in the highest bottles minute slot +1, eg. i have a bottle with 0:9:32 and three other new bottles. the new bottles will not tick past 10 seconds, but when the first bottle gets to 0:10:xx the other bottles will tick up to 11 seconds before resetting their timers.

**Comment by TacocaTYT** [comment]
hmm upon further looking it doesnt matter the minute they always reset at the next time they should hit 10 seconds, never shwoing mreo thatn a 9 in their seconds dlot
this resets the full bottle for some reason
this makes them vaguely useless

**Comment by haoict** [comment]
this is intended for making the mod balance. you can only have one bottle

**Comment by TacocaTYT** [comment]
Perhaps add some flavour text somewhere that mentions something about the bottles becoming unstable if moer than one is present? or add a config option that allows multiple?
